// 在对应位置填写真实素材路径；路径从 public 目录开始，例如 /works/my-image.jpg。
// title / alt 为可选字段；视频可再填 poster。不要把电脑绝对路径填入 src。
export const workMedia = {
  'creative-square-01': { src: '/works/creative-square/01-ultra-basketball.jpg', title: '双子星 · 篮球主题', alt: '绿色篮球场背景，少年持球跃起，搭配双子星液体钙产品与白色标题。' },
  'creative-square-02': { src: '/works/creative-square/02-iron-clouds.png', title: '红皇后 · 云朵铁滴剂', alt: '蓝天白云场景，云朵造型标题、棕色滴剂瓶与张开双臂的儿童。' },
  'creative-square-03': { src: '/works/creative-square/03-ultra-skateboard.jpg', title: '宝嘉力 · 滑板少年', alt: '蓝天与白色飘带之间的滑板少年，左下方陈列液体钙包装。' },
  'creative-square-04': { src: '/works/creative-square/04-fish-oil-arctic.jpg', title: '金凯撒 · 极寒鱼油', alt: '冰洞与雪景中的金色透明胶囊，下方搭配金凯撒鱼油包装与蓝色排版。' },
  'creative-square-05': { src: '/works/creative-square/05-fish-oil-ocean.jpg', title: '金凯撒 · 深海鱼油', alt: '深蓝海底、鱼群和珊瑚环绕鱼油包装，金色胶囊点缀画面。' },
  'creative-square-06': { src: '/works/creative-square/06-calcium-womens-day.jpg', title: '宝嘉力 · 3·8 焕新周', alt: '蓝粉背景上陈列液体钙产品，金色数字 3·8、缎带与花瓣组成活动视觉。' },
  'creative-square-07': { src: '/works/creative-square/07-fish-oil-mini.png', title: '金凯撒 · Mini 鱼油', alt: '蓝色背景与金色胶囊衬托 Mini 鱼油包装，左侧为大字号斜体标题。' },
  'creative-square-08': { src: '/works/creative-square/08-probiotics-child.png', title: '兰骑士 · 儿童益生菌', alt: '蓝天草地场景，穿紫衣的儿童坐在木椅上，搭配紫色益生菌包装。' },
  'creative-square-09': { src: '/works/creative-square/09-probiotics-summer.png', title: '兰骑士 · 夏日主题', alt: '绿色草地纹理与立体曲线背景，搭配益生菌包装、条袋和白绿标题。' },
  'creative-square-10': { src: '/works/creative-square/10-beauty-fish-oil.png', title: '皇家玫瑰 · 美容鱼油', alt: '海边蓝天背景中的白衣女性展示白粉产品包装，搭配白色标题。' },
  'creative-square-11': { src: '/works/creative-square/11-iron-kids.jpg', title: '意之宝 · 少儿铁', alt: '蓝天下的女孩与少儿铁包装，前景以草莓和黄色花朵构成鲜明色彩。' },
  'creative-square-12': { src: '/works/creative-square/12-schubert-gold.jpg', title: '舒伯特 · 金护卫', alt: '白金背景上展示金护卫包装和条袋，金色流线与气泡围绕产品。' },
  'creative-square-13': { src: '/works/creative-square/13-schubert-active.jpg', title: '舒伯特 · 运动主题', alt: '蓝粉背景中穿运动服的女性手持益生菌包装，白色大字与流动飘带呼应。' },
  'creative-square-14': { src: '/works/creative-square/14-growth-collagen.jpg', title: '双子星 · 成长主题', alt: '蓝色跑道上的不同年龄儿童与骨胶原产品包装，搭配黄白标题和金色圆形信息。' },
  'creative-square-15': { src: '/works/creative-square/15-iron-new-year.jpg', title: '意之宝 · 年货节', alt: '深红色年货节画面，女性与红色产品包装搭配金色骏马线条和米色标题。' },
  'creative-square-16': { src: '/works/creative-square/16-mini-capsule.jpg', title: '金凯撒 · Mini 胶囊', alt: '白色背景上，手指捏起一颗金色迷你胶囊，黑色大标题与浅灰 MINI 字样形成简洁排版。' },
  'creative-square-17': { src: '/works/creative-square/17-calcium-maternity.jpg', title: '宝嘉力 · 孕期液体钙', alt: '白绿渐变背景中，孕妇手持绿色条袋，搭配液体钙包装、金色信息圆球与白色飘带。' },
  'creative-square-18': { src: '/works/creative-square/18-iron-maternity.jpg', title: '红皇后 · 孕期补铁', alt: '粉白背景中的孕妇与红白 Ferrolip FORTE 包装，红色流线和血细胞造型围绕产品，底部保留提示文字。' },
  // 沿用 creative-long 编号与锚点；这些是完整竖版海报，不使用超长图阅读模式。
  'creative-long-01': { src: '/works/creative-portrait/01-racing-mountain.png', title: '金凯撒 · 雪山赛车', ratio: '915:1141', alt: '蓝色雪山与金色赛道上的品牌赛车，倾斜的红白标题贯穿画面。' },
  'creative-long-02': { src: '/works/creative-portrait/02-calcium-child.jpg', title: '宝嘉力 · 儿童液体钙', ratio: '750:1052', alt: '蓝天背景中的跳跃儿童与绿色液体钙包装，底部保留产品防伪查询说明。' },
  'creative-long-03': { src: '/works/creative-portrait/03-calcium-active.jpg', title: '宝嘉力 · 活力钙', ratio: '750:1052', alt: '蓝色背景中的跑步男性与活力钙包装，金色展台下方为产品防伪查询说明。' },
  'creative-long-04': { src: '/works/creative-portrait/04-schubert-active.jpg', title: '舒伯特 · 轻盈体态', alt: '运动装女性向前展示益生菌包装，蓝粉渐变背景与流动飘带呼应人物姿态。' },
  'creative-long-05': { src: '/works/creative-portrait/05-beauty-fish-oil.jpg', title: '皇家玫瑰 · 人物海报', alt: '蓝天背景中，白衣女性手持白粉鱼油包装，将胶囊举到嘴边，白色标题围绕人物排布。' },
  'creative-long-06': { src: '/works/creative-portrait/06-fish-oil-gold.jpg', title: '金凯撒 · 金鱼流线', alt: '蓝色水面上的鱼油包装，金色鱼形流线与三颗成分圆球围绕产品。' },
  'creative-long-07': { src: '/works/creative-portrait/07-fish-oil-crown.jpg', title: '金凯撒 · 皇冠金鱼', alt: '戴金色皇冠的鱼形流线环绕鱼油包装，搭配深蓝背景、金色圆球与水花。' },
  'creative-long-08': { src: '/works/creative-portrait/08-football-character.png', title: '金凯撒 · 足球拟人', alt: '鱼油包装化作穿球鞋的角色，在体育场中踢球，搭配红白笔刷标题与金色底部文字。' },
  'creative-long-09': { src: '/works/creative-portrait/09-racing-cream.jpg', title: '金凯撒 · 极速巅峰', alt: '米白背景上，红色斜向标题与品牌赛车形成对角构图，车后拖出黑色轮迹和火花。' },
  'creative-long-10': { src: '/works/creative-portrait/10-fish-oil-press.jpg', title: '金凯撒 · 新闻工作者日', ratio: '1440:1920', alt: '蓝色发布会舞台上，戴墨镜的金色胶囊角色面对多支话筒，顶部排布新闻工作者日主题标题。' },
  'creative-long-11': { src: '/works/creative-portrait/11-iron-vessels.jpg', title: '意之宝 · 铁粉创意', ratio: '750:1000', alt: '银灰背景上，透明管道与红色球体围绕红色 Ferrolip 铁粉包装，搭配深蓝描边标题。' },
  'creative-long-12': { src: '/works/creative-portrait/12-racing-experience.jpg', title: '金凯撒 · 赛车体验', ratio: '4724:7087', alt: '红黑赛道背景中的品牌赛车，红白斜向大字突出赛车体验主题，底部保留活动说明与二维码。' },
  // IP 建议用透明底 PNG / WebP；description 填角色说明，background 可填低饱和背景色。
  'ip-design-01': {
    src: '/works/mind-laugh.png', poster: '', title: 'mind · 大笑',
    alt: '巴康明 mind 戴黄色渔夫帽，闭眼大笑，双手放在身前，抬起一只脚。',
    description: '黄色渔夫帽、绿色手套与圆润的瓶身。用笑眼和舒展的动作，延展角色的表情。',
    background: '#e8e7da',
  },
  'ip-design-02': {
    src: '/works/mind-magic.png', poster: '', title: 'mind · 魔法',
    alt: '巴康明 mind 手持星形魔法棒，帽子周围点缀星光。',
    description: '保持角色的黄绿配色，加入星形魔法棒与细碎星光。',
    background: '#e7e2ee',
  },
  'ip-design-03': {
    src: '/works/mind-like.png', poster: '', title: 'mind · 点赞',
    alt: '巴康明 mind 一手托起产品包装，另一只手竖起大拇指，抬脚向前。',
    description: '一手托起产品，一手竖起拇指。将角色的动作与产品展示结合。',
    background: '#e1e7dd',
  },
  'ip-design-04': {
    src: '/works/mind-hello.png', poster: '', title: 'mind · 打招呼',
    alt: '巴康明 mind 以坐姿抬手打招呼，黄色鞋子向前伸出。',
    description: '以轻松的坐姿和挥手动作，呈现角色的另一种互动表情。',
    background: '#e0e7eb',
  },
  'marketing-main-01': { src: '/works/marketing-main/01-fish-oil-tmall.jpg', title: '金凯撒 · 高纯鱼油主图', ratio: '1:1', alt: '蓝色天猫国际营销主图，鱼油包装与白色信息栏、红色价格区形成鲜明层级。' },
  'marketing-main-02': { src: '/works/marketing-main/02-fish-oil-year-end.jpg', title: '金凯撒 · 年终促销主图', ratio: '1:1', alt: '橙红色年终促销主图，鱼油包装搭配活动标题、礼赠信息和底部价格区。' },
  'marketing-main-03': { src: '/works/marketing-main/03-ferrolip-forte.jpg', title: '红皇后 · 补铁营销主图', ratio: '1:1', alt: '红粉色天猫国际主图，红裙女性与 Ferrolip FORTE 包装并列，配有产品信息和促销价格。' },
  'marketing-main-04': { src: '/works/marketing-main/04-mini-fish-oil-jd.jpg', title: '金凯撒 · 京东 Mini 鱼油主图', ratio: '1:1', alt: '红蓝配色的京东营销主图，足球场上的 Mini 鱼油包装搭配皇冠与预约礼赠信息。' },
  'marketing-main-05': { src: '/works/marketing-main/05-made-heart-5l.jpg', title: '麦德哈特 · 5L 制氧机主图', ratio: '1:1', alt: '白蓝色麦德哈特制氧机主图，右侧为白色产品，左侧以黑蓝标题和橙色价格展示信息。' },
  'marketing-main-06': { src: '/works/marketing-main/06-made-heart-7l.jpg', title: '麦德哈特 · 7L 制氧机主图', ratio: '1:1', alt: '浅灰背景上的麦德哈特制氧机，左侧为黑色大字产品信息，底部红白区域呈现价格与服务。' },
  'livestream-design-01': { src: '/works/livestream-design/01-calcium-spring.jpg', title: '宝嘉力 · 春季直播间', ratio: '1080:1920', alt: '薄荷绿春季直播间，花卉、展示屏与液体钙包装搭配，保留顶部标题及底部服务说明。' },
  'livestream-design-02': { src: '/works/livestream-design/02-calcium-new-year.jpg', title: '宝嘉力 · 马年直播间', ratio: '1080:1920', alt: '红金色马年主题直播间，中央金色骏马与产品展台呼应，左右排列信息卡片。' },
  'livestream-design-03': { src: '/works/livestream-design/03-fish-oil-sports.gif', title: '金凯撒 · 运动直播间', ratio: '900:1600', alt: '蓝色运动主题直播间动态图，球类装饰、健身器械与鱼油包装组成场景，下方保留品牌与服务信息。' },
  'content-optimization-01': { src: '/works/content-optimization/01-probiotic-awards.jpg', title: '宝西兰 · 益生菌获奖展示', ratio: '790:1624', alt: '金棕色版面中，奖杯、奖牌与宝西兰益生菌包装上下排列，保留全部标题及说明。' },
  'content-optimization-02': { src: '/works/content-optimization/02-fish-oil-arctic.jpg', title: '金凯撒 · 极寒品质展示', ratio: '1200:1600', alt: '冰蓝色海面背景、立体冰字与鱼油包装构成的品质展示版面。' },
  'content-optimization-03': { src: '/works/content-optimization/03-fish-oil-nutrition.png', title: '鱼油 · 纯度与营养信息', ratio: '790:1333', alt: '白色背景中，金色鱼油胶囊环绕产品包装，深蓝标题与底部说明完整呈现。' },
  'exhibition-01': { src: '/works/exhibition/01-uga-vitafoods-asia.jpg', title: 'UGA · Vitafoods Asia 01', ratio: '3508:2058', alt: 'UGA 展台效果图，环形品牌吊楣下设有蓝白主墙、红色产品墙、接待台与洽谈区，展示展台一侧的整体空间。' },
  'exhibition-02': { src: '/works/exhibition/02-uga-vitafoods-asia.jpg', title: 'UGA · Vitafoods Asia 02', ratio: '4961:2910', alt: 'UGA 展台另一视角，前景为蓝白接待台和产品展柜，后方蓝红品牌墙、洽谈桌椅与环形吊楣形成完整展示空间。' },
  'exhibition-03': { src: '/works/exhibition/03-sunseasons-vitafoods.jpg', title: '阳光四季 · Vitafoods 01', ratio: '12500:6942', alt: '黑色背景中的阳光四季展台效果图，白色开放式顶部框架搭配绿色品牌标识、女性人物海报、产品展示墙与洽谈区。' },
  'exhibition-04': { src: '/works/exhibition/04-sunseasons-vitafoods.jpg', title: '阳光四季 · Vitafoods 02', ratio: '12500:6942', alt: '阳光四季展台效果图，白绿展台中陈列儿童篮球主题与家庭草地主题海报，左侧紫色益生菌展示墙与中央接待台呼应。' },
  'logo-design-01': { src: '/works/logo-design/01-meizhili-logo-construction.jpg', title: '美之莉 · Logo结构研究', ratio: '4096:2304', alt: '美之莉品牌标志结构研究页面，以黑白线稿展示蝴蝶形标志的曲线、留白、图文组合与比例关系。' },
  'logo-design-02': { src: '/works/logo-design/02-meizhili-logo-application.png', title: '美之莉 · Logo应用展示', ratio: '4096:2304', alt: '米白色品牌应用场景中展示金色美之莉标志，包括立体墙面字、手提袋和名片效果。' },
  'logo-design-03': { src: '/works/logo-design/03-widar-logo-construction.jpg', title: '薇达 · Logo结构研究', ratio: '4096:2304', alt: '薇达 WIDAR 品牌标志结构研究页面，以黑白线稿展示中英文字形框架、曲线细节与组合对齐关系。' },
  'logo-design-04': { src: '/works/logo-design/04-widar-logo-application.png', title: '薇达 · Logo应用展示', ratio: '1672:941', alt: '米白色品牌空间与纸品场景中展示黑色薇达 WIDAR 标志，包括立体墙面字、包装盒、礼盒和名片效果。' },
  'packaging-design-01': { src: '/works/packaging-design/01-meizhili-blue-green-haircare.jpg', title: '美之莉 · 蓝绿洗护系列包装', ratio: '5729:8023', splitY: 4012, draftAlt: '灰色背景上的美之莉蓝绿洗护系列包装平面稿，包含精油、洗发水、护发素和头皮精华四种瓶型。', renderAlt: '明亮白色场景中的美之莉蓝绿洗护系列包装3D效果图，四种产品按高低顺序陈列。' },
  'packaging-design-02': { src: '/works/packaging-design/02-meizhili-green-gold-haircare.jpg', title: '美之莉 · 绿金洗护系列包装', ratio: '5729:8018', splitY: 4000, draftAlt: '灰色背景上的美之莉绿金洗护系列包装平面稿，包含精油、洗发水、护发素和头皮精华四种瓶型。', renderAlt: '暖色光影场景中的美之莉绿金洗护系列包装3D效果图，四种产品以玻璃、白色瓶身和金色泵头呈现。' },
  'china-gt-racing-01': { src: '/works/china-gt-racing/01-racing-rear-view.jpg', title: 'China GT · 赛车后视图', ratio: '5504:3072', alt: 'China GT 项目赛车后视图，白蓝红车身涂装搭配品牌标识与大型尾翼。' },
  'china-gt-racing-02': { src: '/works/china-gt-racing/02-racing-multi-view.jpg', title: 'China GT · 赛车多视图', ratio: '5504:3072', alt: 'China GT 项目赛车俯视图与左右侧视图组合，完整展示白蓝红车身涂装及品牌信息布局。' },
  'china-gt-racing-03': { src: '/works/china-gt-racing/03-racing-left-front-view.jpg', title: 'China GT · 赛车左前视图', ratio: '5504:3072', alt: 'China GT 项目赛车左前方视角，展示白蓝红涂装、车门品牌标识、轮毂与尾翼细节。' },
  'china-gt-racing-04': { src: '/works/china-gt-racing/04-racing-right-front-view.jpg', title: 'China GT · 赛车右前视图', ratio: '5504:3072', alt: 'China GT 项目赛车右前方视角，展示白蓝红涂装、车头编号、车身品牌标识与空气动力套件。' },
  'homepage-01': { src: '/works/homepage/01-double-eleven-medical.png', title: '医疗器械 · 双11首页', ratio: '1200:5846', alt: '蓝橙配色的医疗器械双11店铺首页，展示制氧机与呼吸机，以及活动时间、产品优惠和会员购物攻略。' },
  'homepage-02': { src: '/works/homepage/02-calcium-womens-day.jpg', title: '宝嘉力 · 3·8首页', ratio: '1200:6381', alt: '宝嘉力液体钙3·8开门红店铺首页，红金色主视觉搭配液体钙产品、预售礼赠与会员积分福利。' },
  'homepage-03': { src: '/works/homepage/03-calcium-jd-618.jpg', title: '宝嘉力 · 京东618首页', ratio: '1200:5967', alt: '宝嘉力京东618店铺首页，红金配色的产品购物车主视觉，下接会员优惠券、积分兑换及满赠活动。' },
  'product-manual-01': { src: '/works/product-manual/inositol-01.png', title: '肌醇手册 · 品牌封面', ratio: '6000:3375', alt: '粉白渐变背景上的肌醇产品手册封面，左侧产品包装，右侧品牌标题，下方为粉色流体装饰。' },
  'product-manual-02': { src: '/works/product-manual/inositol-02.png', title: '肌醇手册 · 主题介绍', ratio: '6000:3375', alt: '肌醇手册第二页，左侧主题标题与介绍文字，右侧为女性面部特写。' },
  'product-manual-03': { src: '/works/product-manual/inositol-03.png', title: '肌醇手册 · 目录', ratio: '6000:3375', alt: '粉白渐变目录页，中英文目录标题与五个章节名称以细线分隔。' },
  'product-manual-04': { src: '/works/product-manual/inositol-04.png', title: '肌醇手册 · 危机溯源', ratio: '6000:3375', alt: '肌醇手册第一部分章节页，粉色 PART 01 与危机溯源标题居中排列。' },
  'product-manual-05': { src: '/works/product-manual/inositol-05.png', title: '肌醇手册 · 问题引入', ratio: '6000:3375', alt: '粉色你知道吗标题配合浅色问号图形，下方保留引入文字和页脚。' },
  'product-manual-06': { src: '/works/product-manual/inositol-06.png', title: '肌醇手册 · 信息解析', ratio: '6000:3375', alt: '左侧三组粉色小标题与说明文字，右侧为透明粉色立体气泡，底部保留来源说明。' },
  'product-manual-07': { src: '/works/product-manual/inositol-07.png', title: '肌醇手册 · 品牌愿景', ratio: '6000:3375', alt: '肌醇手册第二部分章节页，粉色 PART 02 与品牌愿景标题居中排列。' },
  'product-manual-08': { src: '/works/product-manual/inositol-08.png', title: '肌醇手册 · 品牌介绍', ratio: '6000:3375', alt: '左侧品牌标题与说明文字，右侧为手持粉色产品条包的女性。' },
  'product-manual-09': { src: '/works/product-manual/inositol-09.png', title: '肌醇手册 · 卵巢秘密', ratio: '6000:3375', alt: '肌醇手册第三部分章节页，粉色 PART 03 与卵巢秘密标题居中排列。' },
  'product-manual-11': { src: '/works/product-manual/inositol-11.png', title: '肌醇手册 · 肌醇介绍', ratio: '6000:3375', alt: '左侧肌醇介绍标题与正文，右侧为粉色透明气泡，画面保持粉白渐变。' },
  'product-manual-12': { src: '/works/product-manual/inositol-12.png', title: '肌醇手册 · 成分解析', ratio: '6000:3375', alt: '透明粉色立体示意图居中，两侧排列 MYO 肌醇和 D-手性肌醇的介绍，底部保留来源说明。' },
  'product-manual-25': { src: '/works/product-manual/inositol-25.png', title: '肌醇手册 · 荣誉展示', ratio: '6000:3375', alt: '粉色荣誉展示页，左侧奖杯与产品组合，右侧为证书，底部保留说明文字。' },
  'product-manual-28': { src: '/works/product-manual/inositol-28.png', title: '肌醇手册 · 封底', ratio: '6000:3375', alt: '肌醇手册结束页，左侧为透明流体包裹的产品包装，右侧为感谢观看与 THANKS。' },
  'sunseasons-manual-01': { src: '/works/sunseasons-manual/sunseasons-01.png', title: '宝嘉力产品手册 · 封面', ratio: '8054:4530', alt: '绿色手册封面，左侧为黄色 Sun Seasons 标识，右侧为白色英文标题。' },
  'sunseasons-manual-02': { src: '/works/sunseasons-manual/sunseasons-02.png', title: '宝嘉力产品手册 · 集团简介', ratio: '8054:4530', alt: '左侧是孩子在草地上奔跑与风车的照片，右侧为绿色集团简介标题和正文。' },
  'sunseasons-manual-03': { src: '/works/sunseasons-manual/sunseasons-03.png', title: '宝嘉力产品手册 · 产品保障', ratio: '8054:4530', alt: '白底绿字的信息排版，左侧分组文字，右侧为实验室与研究人员照片拼版。' },
  'sunseasons-manual-05': { src: '/works/sunseasons-manual/sunseasons-05.png', title: '宝嘉力产品手册 · 品牌介绍', ratio: '8054:4530', alt: '绿色品牌章节页，白色中英文标题靠左，右下角为黄色宝嘉力文字。' },
  'sunseasons-manual-06': { src: '/works/sunseasons-manual/sunseasons-06.png', title: '宝嘉力产品手册 · 品牌荣誉', ratio: '8054:4530', alt: '绿色荣誉主题页面，白色大标题搭配金色奖杯、证书与产品包装。' },
  'sunseasons-manual-07': { src: '/works/sunseasons-manual/sunseasons-07.png', title: '宝嘉力产品手册 · 品牌简介', ratio: '8054:4530', alt: '上方为一家四口围坐餐桌的生活场景，下方为绿色品牌简介标题与说明文字。' },
  'sunseasons-manual-08': { src: '/works/sunseasons-manual/sunseasons-08.png', title: '宝嘉力产品手册 · 产品简介', ratio: '8054:4530', alt: '浅绿色产品介绍页面，右侧为倾斜的液体钙条包，底部点缀白色流体与柠檬。' },
  'sunseasons-manual-09': { src: '/works/sunseasons-manual/sunseasons-09.png', title: '宝嘉力产品手册 · 数据图表', ratio: '8054:4533', alt: '白底绿色标题下方分三栏展示彩色立体柱状图、比例图和金字塔图表。' },
  'sunseasons-manual-13': { src: '/works/sunseasons-manual/sunseasons-13.png', title: '宝嘉力产品手册 · 技术荣誉', ratio: '8054:4530', alt: '浅绿色页面左侧排列技术介绍文字，右侧为金色奖杯与枫叶奖牌，底部为白色流体。' },
  'sunseasons-manual-14': { src: '/works/sunseasons-manual/sunseasons-14.png', title: '宝嘉力产品手册 · 专利展示', ratio: '8054:4530', alt: '浅绿白色背景，三份专利证书与金色奖杯、产品包装分层陈列。' },
  'sunseasons-manual-16': { src: '/works/sunseasons-manual/sunseasons-16.png', title: '宝嘉力产品手册 · 检测展示', ratio: '8054:4530', alt: '上方为实验室场景和绿色标题条，下方排列绿色图标与两份金色边框检测报告。' },
  'sunseasons-manual-25': { src: '/works/sunseasons-manual/sunseasons-25.png', title: '宝嘉力产品手册 · 封底', ratio: '8054:4530', alt: '绿色结束页，白色谢谢观看文字叠在浅色 thanks 字样上，底部为黄色品牌标识。' },
  'ai-video-01': { src: '/works/ai-video/01-ai-video.mp4', title: 'AI 视频创作 · 作品一', ratio: '1080:1440', alt: '' },
  'ai-video-02': { src: '/works/ai-video/02-ai-video.mp4', title: 'AI 视频创作 · 作品二', ratio: '1920:1080', alt: '' },
  'ai-video-03': { src: '/works/ai-video/03-ai-video.mp4', title: 'AI 视频创作 · 作品三', ratio: '1920:1080', alt: '' },
  'ai-video-04': { src: '/works/ai-video/04-ai-video.mp4', title: 'AI 视频创作 · 作品四', ratio: '2560:1440', alt: '' },
  'three-d-scene-01': { src: '/works/three-d-scenes/01-oxygen-concentrator-sofa.jpg', title: '麦德哈特 · 客厅制氧场景', ratio: '1500:2200', alt: '浅色客厅沙发旁摆放白色麦德哈特制氧机，柔和日光在墙面和地毯上形成阴影。' },
  'three-d-scene-02': { src: '/works/three-d-scenes/02-ovaria-plus.jpg', title: 'OVARIA Plus · 产品视觉', ratio: '1400:2126', alt: '白粉渐变背景中，粉色 OVARIA Plus 条袋被半透明粉色流体环绕。' },
  'three-d-scene-03': { src: '/works/three-d-scenes/03-oxygen-concentrator-window.jpg', title: '麦德哈特 · 临窗制氧场景', ratio: '2000:2000', alt: '临湖落地窗前摆放白色麦德哈特制氧机，沙发、木地板、绿地和气泡构成明亮家居场景。' },
  'three-d-scene-04': { src: '/works/three-d-scenes/04-oxygen-concentrator-mountain-room.jpg', title: '麦德哈特 · 山景客厅场景', ratio: '3800:3800', alt: '山景落地窗与浅色沙发旁摆放白色麦德哈特制氧机，木地板和自然光营造安静室内氛围。' },
  'three-d-scene-05': { src: '/works/three-d-scenes/05-home-oxygen-device-chair.jpg', title: '麦德哈特 · 家居桌面场景', ratio: '3800:3800', alt: '原木边桌上展示白色麦德哈特家用设备，旁边为浅色休闲椅、绿植和落地窗。' },
  'three-d-scene-06': { src: '/works/three-d-scenes/06-orange-oxygen-concentrator-winter.jpg', title: '麦德哈特 · 冬日橙色场景', ratio: '3800:5700', alt: '冬日窗景前的木桌上陈列橙色麦德哈特制氧机，周围搭配书本、时钟、杯子和柿子装饰。' },
  'three-d-scene-07': { src: '/works/three-d-scenes/07-oxygen-concentrator-cabinet.jpg', title: '麦德哈特 · 暖阳边柜场景', ratio: '3800:3800', alt: '暖阳照进室内，白色麦德哈特制氧机摆放在原木边柜上，与盆景、画框和绿植组合。' },
  'three-d-scene-08': { src: '/works/three-d-scenes/08-oxygen-concentrator-lounge.jpg', title: '麦德哈特 · 弧形客厅场景', ratio: '3800:3800', alt: '浅色弧形沙发与木质休闲椅围合成客厅，白色麦德哈特制氧机摆放在地毯中央。' },
  'three-d-scene-09': { src: '/works/three-d-scenes/09-oxygen-concentrator-nature.jpg', title: '麦德哈特 · 自然水岸场景', ratio: '3800:3801', alt: '白色麦德哈特制氧机置于水岸草地上，蓝天、水面与蕨类植物构成清新自然场景。' },
  'three-d-motion-01': { src: '/works/three-d-motion/01-motion.mp4', poster: '/works/three-d-motion/01-motion-poster-04s.png', title: '麦德哈特 · 核心部件三维动画', ratio: '1920:1080', alt: '' },
  'three-d-motion-02': { src: '/works/three-d-motion/02-motion-portrait.mp4', title: 'Ladyflora Plus · 产品三维动画', ratio: '1312:1734', alt: '' },
  'three-d-motion-03': { src: '/works/three-d-motion/03-skincare-motion.mp4', title: '护肤产品 · 金色质感动画', ratio: '1280:1186', alt: '' },
  'three-d-motion-04': { src: '/works/three-d-motion/04-motion.mp4', title: '麦德哈特 · 滤芯结构动画', ratio: '1920:1080', alt: '' },
  'three-d-motion-05': { src: '/works/three-d-motion/05-motion.mp4', title: '麦德哈特 · 科技芯片动画', ratio: '1920:1080', alt: '' },
  'three-d-motion-06': { src: '/works/three-d-motion/06-portable-oxygen.gif', title: '麦德哈特 H-L70S · 轻音便携制氧机', ratio: '1080:519', kind: 'image', previewFit: 'contain', alt: '浅蓝色动态画面展示麦德哈特 H-L70S 轻音便携制氧机，配有“无惧高反，轻·岂止于轻”标题。' },
  'product-detail-01': { src: '/works/product-detail/01-317-oxygen.jpg', title: '317 制氧机详情', ratio: '790:22967', alt: '白蓝色制氧机详情页，以产品展示、使用场景、结构示意与参数信息组成完整长图。' },
  'product-detail-02': { src: '/works/product-detail/02-calcium-basketball.jpg', title: '液体钙 · 篮球主题详情', ratio: '1440:31255', alt: '蓝天与绿色篮球主题的液体钙详情页，首屏为持球少年，下接配方介绍、图表与产品信息。' },
  'product-detail-03': { src: '/works/product-detail/03-calcium-maternity.jpg', title: '液体钙 · 孕期主题详情', ratio: '1440:36476', alt: '白绿色孕期液体钙详情页，首屏展示孕妇与产品，下接人物场景、成分示意、图表和参数信息。' },
}
